version: '3.9'

services:
  nginx:
    build: ./Docker/nginx
    volumes:
      - ./:/var/www/sf_app
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - sf_app
    networks:
      - common
  sf_app:
    build:
      context: ./Docker/sf_app
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/sf_app
      - ./Docker/sf_app/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
      - redis
    networks:
      - common
  postgres:
    build: ./Docker/postgres
    ports:
      - 54320:5432
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - common
  redis:
    image: redis:7-alpine
    volumes:
      - /volumes/redis-data:/data
    ports:
      - 6379:6379
    networks:
      - common
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  common:
    driver: bridge