global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'fetch_metrics'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['exams_nginx_1']

rule_files:
  - 'rules/sf_app_rules.yml'
